version: '3.1'

services:
  api:
    container_name: api-rest-v1
    image: api-rest-v1
    build:
      context: .
      dockerfile: ./Dockerfile
    # depends_on:
    #   - database_mysql
    # links:
    #   - database_mysql
    networks:
      app-network:
    ports:
      - "3001:3001"
networks:
  app-network: